#!/usr/bin/env bash

set -e

read -rp "MIT username: " MIT_USER

nmcli connection delete "MIT SECURE" 2>/dev/null || true

nmcli connection add \
  type wifi \
  con-name "MIT SECURE" \
  ssid "MIT SECURE"

nmcli connection modify "MIT SECURE" \
  wifi-sec.key-mgmt wpa-eap \
  802-1x.eap peap \
  802-1x.identity "$MIT_USER" \
  802-1x.phase2-auth mschapv2

nmcli --ask connection up "MIT SECURE"
